<?php
/**
 * StatistiquesApi
 * PHP version 5
 *
 * @category Class
 * @package  Qwenta\Fulleapps
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fulle API
 *
 * <strong>IMPORTANT !<br/>Les requetes externes vers l'API sont susceptibles d'être interrompues en cas de trafic fort sur le serveur !<br/>  Pour éviter ce genre de contraintes, nous pouvons vous intégrer dans notre programme partenaire et vous définir un identifiant Partner, afin de permettre une disponibilité continue de l'API.<br/>  L'identifiant Partner sera à insérer dans un header 'X-Api-Key' : '%ID_PARTNER%'</strong><br/><br/> Pour utiliser l'API en externe, vous devez utiliser la clé utilisateur unique de votre compte commerçant.<br/> Cette clé est disponible à la demande auprés de votre revendeur.<br/> Une fois la clé obtenue, utilisez celle ci dans un header Authorization afin de récupérer et gérer les données de compte via notre API REST.<br/> Pour utiliser l'API avec votre clé, voici un exemple du header à placer : <br/> 'Authorization' : 'Mutual %CLE_UTILISATEUR%'<br/>
 *
 * OpenAPI spec version: 1.0
 * Contact: contact@fulleapps.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.52
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Qwenta\Fulleapps\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Qwenta\Fulleapps\ApiException;
use Qwenta\Fulleapps\Configuration;
use Qwenta\Fulleapps\HeaderSelector;
use Qwenta\Fulleapps\ObjectSerializer;

/**
 * StatistiquesApi Class Doc Comment
 *
 * @category Class
 * @package  Qwenta\Fulleapps
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class StatistiquesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation sales
     *
     * Palmares des ventes
     *
     * @param  \DateTime $from_date Date de début de période (YYYY-MM-DD) (required)
     * @param  \DateTime $to_date Date de fin de période (YYYY-MM-DD) (required)
     * @param  int $id_point_of_sale Identifiant du point de vente associé à la vente (required)
     * @param  int $id_device Identifiant de l&#x27;appareil associé à la vente (required)
     * @param  int $service_number Numéro de service associé à la vente (required)
     * @param  int $id_operator Identifiant de l&#x27;opérateur associé à la vente (required)
     * @param  int $id_sale_method Identifiant du mode de vente associé à la vente (required)
     * @param  int $id_client Identifiant du client associé à la vente (required)
     *
     * @throws \Qwenta\Fulleapps\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Qwenta\Fulleapps\Model\InlineResponse2004
     */
    public function sales($from_date, $to_date, $id_point_of_sale, $id_device, $service_number, $id_operator, $id_sale_method, $id_client)
    {
        list($response) = $this->salesWithHttpInfo($from_date, $to_date, $id_point_of_sale, $id_device, $service_number, $id_operator, $id_sale_method, $id_client);
        return $response;
    }

    /**
     * Operation salesWithHttpInfo
     *
     * Palmares des ventes
     *
     * @param  \DateTime $from_date Date de début de période (YYYY-MM-DD) (required)
     * @param  \DateTime $to_date Date de fin de période (YYYY-MM-DD) (required)
     * @param  int $id_point_of_sale Identifiant du point de vente associé à la vente (required)
     * @param  int $id_device Identifiant de l&#x27;appareil associé à la vente (required)
     * @param  int $service_number Numéro de service associé à la vente (required)
     * @param  int $id_operator Identifiant de l&#x27;opérateur associé à la vente (required)
     * @param  int $id_sale_method Identifiant du mode de vente associé à la vente (required)
     * @param  int $id_client Identifiant du client associé à la vente (required)
     *
     * @throws \Qwenta\Fulleapps\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Qwenta\Fulleapps\Model\InlineResponse2004, HTTP status code, HTTP response headers (array of strings)
     */
    public function salesWithHttpInfo($from_date, $to_date, $id_point_of_sale, $id_device, $service_number, $id_operator, $id_sale_method, $id_client)
    {
        $returnType = '\Qwenta\Fulleapps\Model\InlineResponse2004';
        $request = $this->salesRequest($from_date, $to_date, $id_point_of_sale, $id_device, $service_number, $id_operator, $id_sale_method, $id_client);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Qwenta\Fulleapps\Model\InlineResponse2004',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation salesAsync
     *
     * Palmares des ventes
     *
     * @param  \DateTime $from_date Date de début de période (YYYY-MM-DD) (required)
     * @param  \DateTime $to_date Date de fin de période (YYYY-MM-DD) (required)
     * @param  int $id_point_of_sale Identifiant du point de vente associé à la vente (required)
     * @param  int $id_device Identifiant de l&#x27;appareil associé à la vente (required)
     * @param  int $service_number Numéro de service associé à la vente (required)
     * @param  int $id_operator Identifiant de l&#x27;opérateur associé à la vente (required)
     * @param  int $id_sale_method Identifiant du mode de vente associé à la vente (required)
     * @param  int $id_client Identifiant du client associé à la vente (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function salesAsync($from_date, $to_date, $id_point_of_sale, $id_device, $service_number, $id_operator, $id_sale_method, $id_client)
    {
        return $this->salesAsyncWithHttpInfo($from_date, $to_date, $id_point_of_sale, $id_device, $service_number, $id_operator, $id_sale_method, $id_client)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation salesAsyncWithHttpInfo
     *
     * Palmares des ventes
     *
     * @param  \DateTime $from_date Date de début de période (YYYY-MM-DD) (required)
     * @param  \DateTime $to_date Date de fin de période (YYYY-MM-DD) (required)
     * @param  int $id_point_of_sale Identifiant du point de vente associé à la vente (required)
     * @param  int $id_device Identifiant de l&#x27;appareil associé à la vente (required)
     * @param  int $service_number Numéro de service associé à la vente (required)
     * @param  int $id_operator Identifiant de l&#x27;opérateur associé à la vente (required)
     * @param  int $id_sale_method Identifiant du mode de vente associé à la vente (required)
     * @param  int $id_client Identifiant du client associé à la vente (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function salesAsyncWithHttpInfo($from_date, $to_date, $id_point_of_sale, $id_device, $service_number, $id_operator, $id_sale_method, $id_client)
    {
        $returnType = '\Qwenta\Fulleapps\Model\InlineResponse2004';
        $request = $this->salesRequest($from_date, $to_date, $id_point_of_sale, $id_device, $service_number, $id_operator, $id_sale_method, $id_client);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'sales'
     *
     * @param  \DateTime $from_date Date de début de période (YYYY-MM-DD) (required)
     * @param  \DateTime $to_date Date de fin de période (YYYY-MM-DD) (required)
     * @param  int $id_point_of_sale Identifiant du point de vente associé à la vente (required)
     * @param  int $id_device Identifiant de l&#x27;appareil associé à la vente (required)
     * @param  int $service_number Numéro de service associé à la vente (required)
     * @param  int $id_operator Identifiant de l&#x27;opérateur associé à la vente (required)
     * @param  int $id_sale_method Identifiant du mode de vente associé à la vente (required)
     * @param  int $id_client Identifiant du client associé à la vente (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function salesRequest($from_date, $to_date, $id_point_of_sale, $id_device, $service_number, $id_operator, $id_sale_method, $id_client)
    {
        // verify the required parameter 'from_date' is set
        if ($from_date === null || (is_array($from_date) && count($from_date) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $from_date when calling sales'
            );
        }
        // verify the required parameter 'to_date' is set
        if ($to_date === null || (is_array($to_date) && count($to_date) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $to_date when calling sales'
            );
        }
        // verify the required parameter 'id_point_of_sale' is set
        if ($id_point_of_sale === null || (is_array($id_point_of_sale) && count($id_point_of_sale) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_point_of_sale when calling sales'
            );
        }
        // verify the required parameter 'id_device' is set
        if ($id_device === null || (is_array($id_device) && count($id_device) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_device when calling sales'
            );
        }
        // verify the required parameter 'service_number' is set
        if ($service_number === null || (is_array($service_number) && count($service_number) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $service_number when calling sales'
            );
        }
        // verify the required parameter 'id_operator' is set
        if ($id_operator === null || (is_array($id_operator) && count($id_operator) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_operator when calling sales'
            );
        }
        // verify the required parameter 'id_sale_method' is set
        if ($id_sale_method === null || (is_array($id_sale_method) && count($id_sale_method) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_sale_method when calling sales'
            );
        }
        // verify the required parameter 'id_client' is set
        if ($id_client === null || (is_array($id_client) && count($id_client) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_client when calling sales'
            );
        }

        $resourcePath = '/top_products/statistics';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($from_date !== null) {
            $resourcePath = str_replace(
                '{' . 'from_date' . '}',
                ObjectSerializer::toPathValue($from_date),
                $resourcePath
            );
        }
        // path params
        if ($to_date !== null) {
            $resourcePath = str_replace(
                '{' . 'to_date' . '}',
                ObjectSerializer::toPathValue($to_date),
                $resourcePath
            );
        }
        // path params
        if ($id_point_of_sale !== null) {
            $resourcePath = str_replace(
                '{' . 'id_point_of_sale' . '}',
                ObjectSerializer::toPathValue($id_point_of_sale),
                $resourcePath
            );
        }
        // path params
        if ($id_device !== null) {
            $resourcePath = str_replace(
                '{' . 'id_device' . '}',
                ObjectSerializer::toPathValue($id_device),
                $resourcePath
            );
        }
        // path params
        if ($service_number !== null) {
            $resourcePath = str_replace(
                '{' . 'service_number' . '}',
                ObjectSerializer::toPathValue($service_number),
                $resourcePath
            );
        }
        // path params
        if ($id_operator !== null) {
            $resourcePath = str_replace(
                '{' . 'id_operator' . '}',
                ObjectSerializer::toPathValue($id_operator),
                $resourcePath
            );
        }
        // path params
        if ($id_sale_method !== null) {
            $resourcePath = str_replace(
                '{' . 'id_sale_method' . '}',
                ObjectSerializer::toPathValue($id_sale_method),
                $resourcePath
            );
        }
        // path params
        if ($id_client !== null) {
            $resourcePath = str_replace(
                '{' . 'id_client' . '}',
                ObjectSerializer::toPathValue($id_client),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation fiscalArchives
     *
     * Récupération des archives fiscales
     *
     * @param  int $id_device Identifiant de l&#x27;appareil (required)
     * @param  int $id Identifiant de la ligne archive (Récupération unique) (required)
     * @param  int $filter Type d&#x27;archive (0 &#x3D; Journalière, 1 &#x3D; Mensuelle, 2 &#x3D; Annuelle (Exercice)) (required)
     *
     * @throws \Qwenta\Fulleapps\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function fiscalArchives($id_device, $id, $filter)
    {
        $this->fiscalArchivesWithHttpInfo($id_device, $id, $filter);
    }

    /**
     * Operation fiscalArchivesWithHttpInfo
     *
     * Récupération des archives fiscales
     *
     * @param  int $id_device Identifiant de l&#x27;appareil (required)
     * @param  int $id Identifiant de la ligne archive (Récupération unique) (required)
     * @param  int $filter Type d&#x27;archive (0 &#x3D; Journalière, 1 &#x3D; Mensuelle, 2 &#x3D; Annuelle (Exercice)) (required)
     *
     * @throws \Qwenta\Fulleapps\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function fiscalArchivesWithHttpInfo($id_device, $id, $filter)
    {
        $returnType = '';
        $request = $this->fiscalArchivesRequest($id_device, $id, $filter);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation fiscalArchivesAsync
     *
     * Récupération des archives fiscales
     *
     * @param  int $id_device Identifiant de l&#x27;appareil (required)
     * @param  int $id Identifiant de la ligne archive (Récupération unique) (required)
     * @param  int $filter Type d&#x27;archive (0 &#x3D; Journalière, 1 &#x3D; Mensuelle, 2 &#x3D; Annuelle (Exercice)) (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function fiscalArchivesAsync($id_device, $id, $filter)
    {
        return $this->fiscalArchivesAsyncWithHttpInfo($id_device, $id, $filter)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation fiscalArchivesAsyncWithHttpInfo
     *
     * Récupération des archives fiscales
     *
     * @param  int $id_device Identifiant de l&#x27;appareil (required)
     * @param  int $id Identifiant de la ligne archive (Récupération unique) (required)
     * @param  int $filter Type d&#x27;archive (0 &#x3D; Journalière, 1 &#x3D; Mensuelle, 2 &#x3D; Annuelle (Exercice)) (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function fiscalArchivesAsyncWithHttpInfo($id_device, $id, $filter)
    {
        $returnType = '';
        $request = $this->fiscalArchivesRequest($id_device, $id, $filter);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'fiscalArchives'
     *
     * @param  int $id_device Identifiant de l&#x27;appareil (required)
     * @param  int $id Identifiant de la ligne archive (Récupération unique) (required)
     * @param  int $filter Type d&#x27;archive (0 &#x3D; Journalière, 1 &#x3D; Mensuelle, 2 &#x3D; Annuelle (Exercice)) (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function fiscalArchivesRequest($id_device, $id, $filter)
    {
        // verify the required parameter 'id_device' is set
        if ($id_device === null || (is_array($id_device) && count($id_device) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_device when calling fiscalArchives'
            );
        }
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling fiscalArchives'
            );
        }
        // verify the required parameter 'filter' is set
        if ($filter === null || (is_array($filter) && count($filter) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $filter when calling fiscalArchives'
            );
        }

        $resourcePath = '/archives';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($id_device !== null) {
            $resourcePath = str_replace(
                '{' . 'id_device' . '}',
                ObjectSerializer::toPathValue($id_device),
                $resourcePath
            );
        }
        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }
        // path params
        if ($filter !== null) {
            $resourcePath = str_replace(
                '{' . 'filter' . '}',
                ObjectSerializer::toPathValue($filter),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation taxes
     *
     * Répartition des taxes
     *
     * @param  \DateTime $from_date Date de début de période (YYYY-MM-DD) (required)
     * @param  \DateTime $to_date Date de fin de période (YYYY-MM-DD) (required)
     * @param  int $id_point_of_sale Identifiant du point de vente associé à la vente (required)
     * @param  int $id_device Identifiant de l&#x27;appareil associé à la vente (required)
     * @param  int $id_sale_method Identifiant du mode de vente associé à la vente (required)
     *
     * @throws \Qwenta\Fulleapps\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function taxes($from_date, $to_date, $id_point_of_sale, $id_device, $id_sale_method)
    {
        $this->taxesWithHttpInfo($from_date, $to_date, $id_point_of_sale, $id_device, $id_sale_method);
    }

    /**
     * Operation taxesWithHttpInfo
     *
     * Répartition des taxes
     *
     * @param  \DateTime $from_date Date de début de période (YYYY-MM-DD) (required)
     * @param  \DateTime $to_date Date de fin de période (YYYY-MM-DD) (required)
     * @param  int $id_point_of_sale Identifiant du point de vente associé à la vente (required)
     * @param  int $id_device Identifiant de l&#x27;appareil associé à la vente (required)
     * @param  int $id_sale_method Identifiant du mode de vente associé à la vente (required)
     *
     * @throws \Qwenta\Fulleapps\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function taxesWithHttpInfo($from_date, $to_date, $id_point_of_sale, $id_device, $id_sale_method)
    {
        $returnType = '';
        $request = $this->taxesRequest($from_date, $to_date, $id_point_of_sale, $id_device, $id_sale_method);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation taxesAsync
     *
     * Répartition des taxes
     *
     * @param  \DateTime $from_date Date de début de période (YYYY-MM-DD) (required)
     * @param  \DateTime $to_date Date de fin de période (YYYY-MM-DD) (required)
     * @param  int $id_point_of_sale Identifiant du point de vente associé à la vente (required)
     * @param  int $id_device Identifiant de l&#x27;appareil associé à la vente (required)
     * @param  int $id_sale_method Identifiant du mode de vente associé à la vente (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function taxesAsync($from_date, $to_date, $id_point_of_sale, $id_device, $id_sale_method)
    {
        return $this->taxesAsyncWithHttpInfo($from_date, $to_date, $id_point_of_sale, $id_device, $id_sale_method)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation taxesAsyncWithHttpInfo
     *
     * Répartition des taxes
     *
     * @param  \DateTime $from_date Date de début de période (YYYY-MM-DD) (required)
     * @param  \DateTime $to_date Date de fin de période (YYYY-MM-DD) (required)
     * @param  int $id_point_of_sale Identifiant du point de vente associé à la vente (required)
     * @param  int $id_device Identifiant de l&#x27;appareil associé à la vente (required)
     * @param  int $id_sale_method Identifiant du mode de vente associé à la vente (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function taxesAsyncWithHttpInfo($from_date, $to_date, $id_point_of_sale, $id_device, $id_sale_method)
    {
        $returnType = '';
        $request = $this->taxesRequest($from_date, $to_date, $id_point_of_sale, $id_device, $id_sale_method);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'taxes'
     *
     * @param  \DateTime $from_date Date de début de période (YYYY-MM-DD) (required)
     * @param  \DateTime $to_date Date de fin de période (YYYY-MM-DD) (required)
     * @param  int $id_point_of_sale Identifiant du point de vente associé à la vente (required)
     * @param  int $id_device Identifiant de l&#x27;appareil associé à la vente (required)
     * @param  int $id_sale_method Identifiant du mode de vente associé à la vente (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function taxesRequest($from_date, $to_date, $id_point_of_sale, $id_device, $id_sale_method)
    {
        // verify the required parameter 'from_date' is set
        if ($from_date === null || (is_array($from_date) && count($from_date) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $from_date when calling taxes'
            );
        }
        // verify the required parameter 'to_date' is set
        if ($to_date === null || (is_array($to_date) && count($to_date) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $to_date when calling taxes'
            );
        }
        // verify the required parameter 'id_point_of_sale' is set
        if ($id_point_of_sale === null || (is_array($id_point_of_sale) && count($id_point_of_sale) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_point_of_sale when calling taxes'
            );
        }
        // verify the required parameter 'id_device' is set
        if ($id_device === null || (is_array($id_device) && count($id_device) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_device when calling taxes'
            );
        }
        // verify the required parameter 'id_sale_method' is set
        if ($id_sale_method === null || (is_array($id_sale_method) && count($id_sale_method) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_sale_method when calling taxes'
            );
        }

        $resourcePath = '/taxes/statistics';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($from_date !== null) {
            $resourcePath = str_replace(
                '{' . 'from_date' . '}',
                ObjectSerializer::toPathValue($from_date),
                $resourcePath
            );
        }
        // path params
        if ($to_date !== null) {
            $resourcePath = str_replace(
                '{' . 'to_date' . '}',
                ObjectSerializer::toPathValue($to_date),
                $resourcePath
            );
        }
        // path params
        if ($id_point_of_sale !== null) {
            $resourcePath = str_replace(
                '{' . 'id_point_of_sale' . '}',
                ObjectSerializer::toPathValue($id_point_of_sale),
                $resourcePath
            );
        }
        // path params
        if ($id_device !== null) {
            $resourcePath = str_replace(
                '{' . 'id_device' . '}',
                ObjectSerializer::toPathValue($id_device),
                $resourcePath
            );
        }
        // path params
        if ($id_sale_method !== null) {
            $resourcePath = str_replace(
                '{' . 'id_sale_method' . '}',
                ObjectSerializer::toPathValue($id_sale_method),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getRubricStatistics
     *
     * Rubriques de vente
     *
     * @param  \Qwenta\Fulleapps\Model\RubricsStatisticsBody $body body (optional)
     *
     * @throws \Qwenta\Fulleapps\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Qwenta\Fulleapps\Model\InlineResponse2005
     */
    public function getRubricStatistics($body = null)
    {
        list($response) = $this->getRubricStatisticsWithHttpInfo($body);
        return $response;
    }

    /**
     * Operation getRubricStatisticsWithHttpInfo
     *
     * Rubriques de vente
     *
     * @param  \Qwenta\Fulleapps\Model\RubricsStatisticsBody $body (optional)
     *
     * @throws \Qwenta\Fulleapps\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Qwenta\Fulleapps\Model\InlineResponse2005, HTTP status code, HTTP response headers (array of strings)
     */
    public function getRubricStatisticsWithHttpInfo($body = null)
    {
        $returnType = '\Qwenta\Fulleapps\Model\InlineResponse2005';
        $request = $this->getRubricStatisticsRequest($body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Qwenta\Fulleapps\Model\InlineResponse2005',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getRubricStatisticsAsync
     *
     * Rubriques de vente
     *
     * @param  \Qwenta\Fulleapps\Model\RubricsStatisticsBody $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getRubricStatisticsAsync($body = null)
    {
        return $this->getRubricStatisticsAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getRubricStatisticsAsyncWithHttpInfo
     *
     * Rubriques de vente
     *
     * @param  \Qwenta\Fulleapps\Model\RubricsStatisticsBody $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getRubricStatisticsAsyncWithHttpInfo($body = null)
    {
        $returnType = '\Qwenta\Fulleapps\Model\InlineResponse2005';
        $request = $this->getRubricStatisticsRequest($body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getRubricStatistics'
     *
     * @param  \Qwenta\Fulleapps\Model\RubricsStatisticsBody $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getRubricStatisticsRequest($body = null)
    {

        $resourcePath = '/rubrics/statistics';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
