<?php
/**
 * PointOfSaleTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Qwenta\Fulleapps
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fulle API
 *
 * <strong>IMPORTANT !<br/>Les requetes externes vers l'API sont susceptibles d'être interrompues en cas de trafic fort sur le serveur !<br/>  Pour éviter ce genre de contraintes, nous pouvons vous intégrer dans notre programme partenaire et vous définir un identifiant Partner, afin de permettre une disponibilité continue de l'API.<br/>  L'identifiant Partner sera à insérer dans un header 'X-Api-Key' : '%ID_PARTNER%'</strong><br/><br/> Pour utiliser l'API en externe, vous devez utiliser la clé utilisateur unique de votre compte commerçant.<br/> Cette clé est disponible à la demande auprés de votre revendeur.<br/> Une fois la clé obtenue, utilisez celle ci dans un header Authorization afin de récupérer et gérer les données de compte via notre API REST.<br/> Pour utiliser l'API avec votre clé, voici un exemple du header à placer : <br/> 'Authorization' : 'Mutual %CLE_UTILISATEUR%'<br/>
 *
 * OpenAPI spec version: 1.0
 * Contact: contact@fulleapps.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.52
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Qwenta\Fulleapps;

use PHPUnit\Framework\TestCase;

/**
 * PointOfSaleTest Class Doc Comment
 *
 * @category    Class
 * @description Class PointOfSale
 * @package     Qwenta\Fulleapps
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PointOfSaleTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PointOfSale"
     */
    public function testPointOfSale()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "id_country"
     */
    public function testPropertyIdCountry()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "name_webshop"
     */
    public function testPropertyNameWebshop()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "postal"
     */
    public function testPropertyPostal()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "website"
     */
    public function testPropertyWebsite()
    {
    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {
    }

    /**
     * Test attribute "phone_2"
     */
    public function testPropertyPhone2()
    {
    }

    /**
     * Test attribute "company_identification"
     */
    public function testPropertyCompanyIdentification()
    {
    }

    /**
     * Test attribute "activity_identification"
     */
    public function testPropertyActivityIdentification()
    {
    }

    /**
     * Test attribute "tax_identification"
     */
    public function testPropertyTaxIdentification()
    {
    }

    /**
     * Test attribute "logo_base64"
     */
    public function testPropertyLogoBase64()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "legal_form"
     */
    public function testPropertyLegalForm()
    {
    }

    /**
     * Test attribute "share_capital"
     */
    public function testPropertyShareCapital()
    {
    }

    /**
     * Test attribute "webshop_display_mode"
     */
    public function testPropertyWebshopDisplayMode()
    {
    }

    /**
     * Test attribute "has_alcool"
     */
    public function testPropertyHasAlcool()
    {
    }

    /**
     * Test attribute "enable_order"
     */
    public function testPropertyEnableOrder()
    {
    }

    /**
     * Test attribute "enable_credit"
     */
    public function testPropertyEnableCredit()
    {
    }
}
